### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by danilolutz** [city-halls/scraper#4]
Embed the project inside a Docker.

**Comment by jdbohrman** [comment]
I can help with this

**Comment by danilolutz** [comment]
Very nice, any help will be appreciated. Thank you!

**Comment by jdbohrman** [comment]
@danilolutz Absolutely, I just got home so I'm about to dive in on this!

**Comment by danilolutz** [comment]
Done! Thanks @jdbohrman
